<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-7ACLBJR" name="Test" tests="5" failures="1" timestamp="29 Jul 2022 09:13:40 GMT" time="0.049" errors="0">
  <testcase name="sample1" time="0.011" classname="org.cgtestng.PutInGrp"/>
  <testcase name="sample2" time="0.001" classname="org.cgtestng.PutInGrp"/>
  <testcase name="sample3" time="0.013" classname="org.cgtestng.PutInGrp">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
	at graphql.Assert.assertTrue(Assert.java:85)
	at org.cgtestng.PutInGrp.sample3(PutInGrp.java:28)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- sample3 -->
  <testcase name="sample4" time="0.001" classname="org.cgtestng.PutInGrp"/>
  <testcase name="sample5" time="0.001" classname="org.cgtestng.PutInGrp"/>
</testsuite> <!-- Test -->
